### DISCUSSION TITLE
Plugin Storage

### DISCUSSION THREAD

**Discussion by alexanderson1993** [Thorium-Sim/thorium-nova#75] [Ideas] [answered]
This is a technical discussion related to how plugin configuration is stored.

Thorium Classic used a single .json file to store its entire database. While this made it really simple to transfer the database, it caused problems when the file got especially large. Every asset was stored in a single folder, all clumped together.

Thorium Nova Prime tried to address this by separating each flight and each plugin into its own .json file. All of the assets are stored in the same folder as the plugin that uses them. I think this would be sufficient to address the downsides of Thorium Classic, but I think it could be better. 

Here's the proposal:

Almost every object in the database is stored in its own separate file. This includes
- Ship systems
- Ships
- Themes
- Solar Systems

etc. etc.

That last point might raise questions: How granular are we talking here? Does the solar system file contain everything in the entire solar system? Or are there separate files for each of the stars, planets, and other objects? There seem to be benefits and drawbacks to both approaches.

What about assets? If we're separating out each ship, then it makes sense to also store the assets for each ship alongside the text config file. That means each objects would be stored in folders with a text config file and all of the associated assets.

Asset dependencies (like ship systems that a ship depends on) would also be important to figure out. If you delete a ship system from the file system, it is considered removed from the plugin. What about the ship's dependency? It seems to me the easiest solution is to treat the dependency as if it doesn't exist on the ship. If you deleted the warp engine system, any ships with that system would be unable to jump to warp. However, a note about the missing dependency would be available when the ship is edited so the user knows that something is broken and needs to be fixed. (this is actually necessary regardless of whether we go with this approach or not)

A few benefits to this approach:
- It makes it easier to edit plugins with just a text editor
- It makes it easy to copy/paste items from one plugin to another - literally just copy the file

A few downsides:
- It adds a bit of complexity to the codebase
- It makes things just a little bit more brittle

So, here are the questions we're answering:
- Should we split plugin database files into one file for each object?
- How granular should the definition of an object be? A solar system and everything in it, or one file for each planet, or even more granular than that?
- Would anyone use this, and is it even worth implementing? Or do we expect most people to just use the Thorium Nova UI for plugin writing?
- What format should the database files be in? JSON is my default, but we could explore other formats.
- How should Thorium Nova handle misformatted files?

**Comment by Arcadianer** [comment, marked as answer]
I think I would go for the Kubernetes/Helm approach.
JSON is an absolute blast when it comes to m2m communication, and it is human-readable.
But writing JSON by hand is a bit .... hard. 
If you want to have people write Plugins by hand, I would go for making YAML the plugin file base.

Now to the Kubernetes part. 
I personalty like the way Kubernetes handles different manifests. Each Object in Kubernetes has a specific type and can be described in YAML. Together with the packet manager HELM and a bit of templating you can install any kind of cloud-ready app within seconds, and it is completely production ready.

How would I transfer this to nova.

For every system in the game that should be modifiable within a plugin create a YAML-File-Kind. 
Each YAML file will then represent an instance of that system in the game, with an ID and its specific parameters.

Let's create an example DB for a simple Star system.

We have 3 different kinds of YAML Kinds all belonging to the family of universe objects:
- Star system
- Star
- Planet

In our system i want to create 2 Planets with a single sun.

Lets start with Planet 1.

```
apiVersion: universe/v1
kind: Planet
metadata:
  name: unifa-prime
  labels:
    some: awesome-lables
spec:
  object: sphere
    radius: 2000m
    texture: "some/awesome/texture.png"
  
```

And Planet 2

```
apiVersion: universe/v1
kind: Planet
metadata:
  name: unifa-B
  labels:
    some: awesome-lables
spec:
  object: sphere
    radius: 20m
    texture: "some/awesome/texture-comet.png"
```

Same goes for the sun.

```
apiVersion: universe/v1
kind: Star
metadata:
  name: unifa-a-1
  labels:
    some: awesome-lables
spec:
  object: star
    radius: 20m
    color: #somehexcolor
```

And finally, let's add them together in a Star system.


```
apiVersion: universe/v1
kind: System
metadata:
  name: unifa
  labels:
    some: awesome-lables
spec:
  objects:
    - name: unifa-a-1
        orbit: some-orbital-parameter
    - name: unifa-prime
        orbit: another-parameter
    - name: unifa-b
        orbit: final parameter
```

To create some structure you can even separate them by folders and create folders for each planet with textures, and manifests.

**Reply by alexanderson1993** [reply]
I can see a lot of value to this structure. One addition I would make is including JSON Schema validation, which provides code warnings and autocomplete in VS Code, and which provides documentation for how these files should be constructed. It'll also make it easier to do runtime validation when the files are loaded.

Just as a demonstration, this is what a single ship from Thorium Nova Prime looks like in YAML format.
```yml
---
id: ew1dafhkfhd3qei
pluginId: fb9r5prkf6p54xq
components:
  isShip:
    mass: 2000
    nameGeneratorPhrase: d241mgjkhbz9gk2
    category: Cruiser
  alertLevel:
    alertLevel: '5'
    alertLevelLock: false
  identity:
    name: Astra Battleship
    description: Boldly going where no one has gone before.
  tags:
    tags: []
  theme:
    value: default
  shipAssets:
    model: model.glb
    side: side.png
    top: top.png
    logo: logo.svg
    vanity: vanity.png
  size:
    value: 1
  shipSystems:
    systemIds:
    - fb9r5prkf6p5ghh
    - fb9r5prkf6p5k75
    - fb9r5prkf6p5ik1
    - fb9r5prkf6p5bg7
    - 5dw3tsjkgh5owpi
```

Not too bad. The hardest thing is obviously the references, but hopefully switching from opaque IDs to named references would make this a little bit easier to read, although I would include the plugin ID in the reference as well to make cross-plugin references possible.

You just have to hope nobody decides to make two things with the exact same name, I suppose.

**Reply by alexanderson1993** [reply]
I think I'm going to modify the way objects are stored. Instead of just throwing all of their components on there, we'll structure them just a little bit more explicitly. Here's the YAML output for the ship class that I'm working on, based on the properties that I had added up to this point in Thorium Nova Prime.

```yaml
apiVersion: ship/v1
kind: ship
name: Unnamed Ship
description: Boldly going where no one has gone before.
category: Cruiser
tags: []
assets:
  logo: ""
  model: ""
  topView: ""
  sideView: ""
mass: 700000000
length: 350
shipSystems: []
```

That seems easy to understand, easier to verify, and the docs can clarify what each property is supposed to be. When this is loaded into Thorium Nova and used to spawn a ship, it will map these properties to the components on the new ship entity.

**Reply by alexanderson1993** [reply]
The trick is making it easy to tell what the units are for each property. Maybe I should suffix each property with the unit name:

```yaml
apiVersion: ship/v1
kind: ship
name: Unnamed Ship
description: Boldly going where no one has gone before.
category: Cruiser
tags: []
assets:
  logoSvg: ""
  modelGlb: ""
  topViewPng: ""
  sideViewPng: ""
massKg: 700000000
lengthM: 350
shipSystems: []
```

Maybe the docs will be good enough, though.
